//! SQL (CREATE TABLE) export for schema visualization.
//!
//! Generates `CREATE TABLE` and `ALTER TABLE ADD CONSTRAINT` statements
//! for all tables and foreign keys in a `SchemaGraph`.

use crate::graph::{FkEdge, SchemaGraph, TableNode, TableNodeId, format_column_list};

/// SQL export scope (mirrors `DbmlScope`).
#[derive(Clone, Copy, Debug)]
pub enum SqlScope {
    /// Only the focal table and its immediate neighbors.
    FocalTable,
    /// The entire loaded subgraph.
    Subgraph,
    /// Full schema export.
    FullSchema,
}

/// Convert a SchemaGraph to SQL DDL text (CREATE TABLE statements).
pub fn to_sql(graph: &SchemaGraph, scope: SqlScope) -> Result<String, String> {
    let export_graph = match scope {
        SqlScope::FocalTable => {
            if let Some((_focal_idx, focal_node)) = graph.most_connected_node() {
                extract_focal_subgraph(graph, &focal_node.id.name, focal_node.id.schema.as_deref())
            } else {
                return build_sql_text(graph);
            }
        }
        SqlScope::Subgraph | SqlScope::FullSchema => {
            return build_sql_text(graph);
        }
    };

    build_sql_text(&export_graph)
}

/// Extract the focal subgraph: focal table + 1-hop neighbors in both FK directions.
///
/// Delegates to `SchemaGraph::focal_subgraph`, which correctly collects both
/// outgoing FK neighbors (tables the focal table references) and incoming FK
/// neighbors (tables that reference the focal table).
fn extract_focal_subgraph(
    graph: &SchemaGraph,
    focal_name: &str,
    focal_schema: Option<&str>,
) -> SchemaGraph {
    let focal_id = TableNodeId {
        schema: focal_schema.map(String::from),
        name: focal_name.to_string(),
    };

    graph.focal_subgraph(&focal_id)
}

/// Build SQL text from a SchemaGraph.
fn build_sql_text(graph: &SchemaGraph) -> Result<String, String> {
    let mut output = String::new();

    output.push_str("-- SQL DDL generated by DBSpeed\n\n");

    // Sort nodes by fully-qualified name for deterministic output
    let mut nodes: Vec<_> = graph.nodes().collect();
    nodes.sort_by_key(|(_, n)| build_table_name(&n.id));

    // Emit CREATE TABLE for each node
    for (_node_idx, node) in &nodes {
        output.push_str(&build_create_table(node));
        output.push_str("\n\n");
    }

    // Emit ALTER TABLE ADD CONSTRAINT for each FK edge
    for edge in graph.graph.edge_indices() {
        let Some((source_idx, target_idx)) = graph.graph.edge_endpoints(edge) else {
            continue;
        };
        let Some(source_node) = graph.graph.node_weight(source_idx) else {
            continue;
        };
        let Some(target_node) = graph.graph.node_weight(target_idx) else {
            continue;
        };
        let Some(fk_edge) = graph.graph.edge_weight(edge) else {
            continue;
        };

        output.push_str(&build_alter_table_add_fk(source_node, target_node, fk_edge));
        output.push('\n');
    }

    Ok(output)
}

fn build_table_name(id: &TableNodeId) -> String {
    match &id.schema {
        Some(schema) => format!("{}.{}", schema, id.name),
        None => id.name.clone(),
    }
}

fn build_create_table(node: &TableNode) -> String {
    let table_name = build_table_name(&node.id);
    let mut column_defs: Vec<String> = Vec::new();
    let mut pk_columns: Vec<String> = Vec::new();

    for col in &node.columns {
        let mut def = format!("  {} {}", col.name, col.type_name);

        if col.is_pk {
            def.push_str(" NOT NULL");
            pk_columns.push(col.name.clone());
        }

        column_defs.push(def);
    }

    // Composite PK becomes a trailing in-parens clause.
    // Single-PK stays inline as `col NOT NULL` — no separate clause.
    if pk_columns.len() > 1 {
        column_defs.push(format!("  PRIMARY KEY {}", format_column_list(&pk_columns)));
    }

    format!(
        "CREATE TABLE {} (\n{}\n);",
        table_name,
        column_defs.join(",\n")
    )
}

fn build_alter_table_add_fk(
    source_node: &TableNode,
    target_node: &TableNode,
    fk_edge: &FkEdge,
) -> String {
    let source_table = build_table_name(&source_node.id);
    let target_table = build_table_name(&target_node.id);

    let from_cols = fk_edge.from_columns.join(", ");
    let to_cols = fk_edge.to_columns.join(", ");

    let constraint_name = if fk_edge.name.is_empty() {
        format!("fk_{}_{}", source_node.id.name, target_node.id.name)
    } else {
        fk_edge.name.clone()
    };

    let mut sql = format!(
        "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {}",
        source_table, constraint_name, from_cols, target_table
    );
    sql.push_str(&format!("({})", to_cols));

    if let Some(ref on_delete) = fk_edge.on_delete {
        sql.push_str(&format!(" ON DELETE {}", on_delete));
    }
    if let Some(ref on_update) = fk_edge.on_update {
        sql.push_str(&format!(" ON UPDATE {}", on_update));
    }

    sql.push(';');
    sql
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::SchemaGraph;
    use dbflux_core::{ColumnInfo, ForeignKeyInfo, TableInfo};

    fn make_column(name: &str, type_name: &str, is_pk: bool) -> ColumnInfo {
        ColumnInfo {
            name: name.to_string(),
            type_name: type_name.to_string(),
            nullable: !is_pk,
            is_primary_key: is_pk,
            default_value: None,
            enum_values: None,
        }
    }

    fn make_fk(
        name: &str,
        from: Vec<&str>,
        to_table: &str,
        to_schema: Option<&str>,
        to_columns: Vec<&str>,
        on_delete: Option<&str>,
    ) -> ForeignKeyInfo {
        ForeignKeyInfo {
            name: name.into(),
            columns: from.into_iter().map(String::from).collect(),
            referenced_table: to_table.into(),
            referenced_schema: to_schema.map(String::from),
            referenced_columns: to_columns.into_iter().map(String::from).collect(),
            on_delete: on_delete.map(String::from),
            on_update: None,
        }
    }

    fn make_table(name: &str, columns: Vec<ColumnInfo>, fks: Vec<ForeignKeyInfo>) -> TableInfo {
        TableInfo {
            name: name.into(),
            schema: None,
            columns: Some(columns),
            indexes: None,
            foreign_keys: Some(fks),
            constraints: None,
            sample_fields: None,
            storage_hints: None,
            presentation: dbflux_core::CollectionPresentation::default(),
            child_items: None,
            pseudo_columns: Box::default(),
        }
    }

    #[test]
    fn test_sql_single_table() {
        let table = make_table(
            "users",
            vec![
                make_column("id", "serial", true),
                make_column("email", "varchar(255)", false),
            ],
            vec![],
        );

        let graph = SchemaGraph::build(&[table]);
        let sql = to_sql(&graph, SqlScope::Subgraph).expect("SQL export should succeed");

        assert!(sql.contains("CREATE TABLE users"));
        assert!(sql.contains("id serial NOT NULL"));
        assert!(sql.contains("email varchar(255)"));
        // For single-column PK, we emit NOT NULL inline (no separate PRIMARY KEY clause)
    }

    #[test]
    fn test_sql_foreign_key() {
        let a = make_table("a", vec![make_column("id", "serial", true)], vec![]);

        let b = make_table(
            "b",
            vec![
                make_column("id", "serial", true),
                make_column("a_id", "integer", false),
            ],
            vec![make_fk(
                "fk_b_a",
                vec!["a_id"],
                "a",
                None,
                vec!["id"],
                Some("CASCADE"),
            )],
        );

        let graph = SchemaGraph::build(&[a, b]);
        let sql = to_sql(&graph, SqlScope::Subgraph).expect("SQL export should succeed");

        assert!(sql.contains("CREATE TABLE a"));
        assert!(sql.contains("CREATE TABLE b"));
        assert!(sql.contains("ALTER TABLE b ADD CONSTRAINT fk_b_a"));
        assert!(sql.contains("REFERENCES a(id)"));
        assert!(sql.contains("ON DELETE CASCADE"));
    }

    #[test]
    fn test_sql_single_pk() {
        let table = make_table(
            "users",
            vec![
                make_column("id", "integer", true),
                make_column("name", "text", false),
            ],
            vec![],
        );

        let graph = SchemaGraph::build(&[table]);
        let sql = to_sql(&graph, SqlScope::Subgraph).expect("SQL export should succeed");

        // Must open with ( and close with ); — no { or }
        assert!(
            !sql.contains('{') && !sql.contains('}'),
            "DDL must not contain brace characters, got:\n{}",
            sql
        );
        // Single-PK: NOT NULL inline, no standalone PRIMARY KEY clause in the block
        assert!(
            sql.contains("id integer NOT NULL"),
            "PK column must carry NOT NULL inline, got:\n{}",
            sql
        );
        // Nullable column has no modifier
        assert!(
            sql.contains("name text"),
            "nullable column must appear without NOT NULL, got:\n{}",
            sql
        );
        // Normalized structure: must have CREATE TABLE users ( ... );
        let normalized = sql.split_whitespace().collect::<Vec<_>>().join(" ");
        assert!(
            normalized.contains("CREATE TABLE users ("),
            "DDL must open with CREATE TABLE users (, got normalized:\n{}",
            normalized
        );
        assert!(
            normalized.contains(");"),
            "DDL must close with );, got normalized:\n{}",
            normalized
        );
    }

    #[test]
    fn test_sql_composite_pk() {
        // All PK columns must have is_pk = true so the composite-PK branch is exercised.
        let table = make_table(
            "line_items",
            vec![
                make_column("order_id", "integer", true),
                make_column("line_id", "integer", true),
                make_column("qty", "integer", false),
            ],
            vec![],
        );

        let graph = SchemaGraph::build(&[table]);
        let sql = to_sql(&graph, SqlScope::Subgraph).expect("SQL export should succeed");

        // No brace characters
        assert!(
            !sql.contains('{') && !sql.contains('}'),
            "DDL must not contain brace characters, got:\n{}",
            sql
        );

        // Composite PRIMARY KEY clause must appear inside the parentheses.
        // Normalize whitespace to avoid brittleness.
        let normalized = sql.split_whitespace().collect::<Vec<_>>().join(" ");
        assert!(
            normalized.contains("PRIMARY KEY (order_id, line_id)"),
            "composite PK clause must appear inside the table block, got normalized:\n{}",
            normalized
        );

        // Both PK columns must carry NOT NULL.
        assert!(
            sql.contains("order_id integer NOT NULL"),
            "first PK column must carry NOT NULL, got:\n{}",
            sql
        );
        assert!(
            sql.contains("line_id integer NOT NULL"),
            "second PK column must carry NOT NULL, got:\n{}",
            sql
        );

        // Non-PK column has no NOT NULL.
        assert!(
            !sql.contains("qty integer NOT NULL"),
            "non-PK column must not carry NOT NULL, got:\n{}",
            sql
        );

        assert!(
            sql.contains("CREATE TABLE line_items"),
            "table header must be present, got:\n{}",
            sql
        );
    }
}
